---
# tasks file for cAdvisor
- name: run go app containers
  docker_container:
      name: cadvisor
      image: google/cadvisor:latest
      state: started
      detach: True
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
        - /dev/disk/:/dev/disk:ro
      port:
          "8080:8080"
