---
# tasks file for aws
- name: create key
  ec2_key:
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    name: goApp
    region: "{{ aws_region }}"
    state: present
  register: ec2_key

- name: save private key
  copy:
       content: "{{ ec2_key.key.private_key }}"
       dest: "group_vars/goApp.pem"
       mode: 0600
  when: ec2_key.changed

- name: create VM
  ec2:
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    instance_type: "{{instance_type}}"
    image: "{{ ami_id }}"
    wait: true
    exact_count: "{{exact_count_of_vms}}"
    count_tag: goApp
    region: "{{ aws_region }}"
    vpc_subnet_id: "{{subnet_id}}"
    key_name: goApp
    instance_tags:
            Name: GoWebbApp
    assign_public_ip: yes
  register: ec2

- name: print public IP
  debug:
     var: "{{ item.public_ip }}"
  with_items: "{{ ec2.instances }}"

- name: Create SSH Group to login dynamically to EC2 Instance
  add_host:
     hostname: "{{ item.public_ip }}"
     groupname: ec2_go
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  local_action: wait_for
                host={{ item.public_ip }}
                port=22
                state=started
  with_items: "{{ ec2.instances }}"
